package com.example.hoophubskeleton.model

data class User(
    val uid: String = "",                 // Unique ID generated by Firebase
    val name: String = "",                // Name of the user
    val age: Int = 0,                     // Age of the user
    val email: String = "",               // Email of the user
    val competitionLevel: String = "",    // Competition level (e.g., Beginner, Casual, Competitive)
    val location: String = "",            // Location of the user
    val profilePicUrl: String = ""        // URL to the profile picture stored in Firebase Storage
)
